export async function seedIndustries(prisma) {
  await prisma.industry.createMany({
    data: [
      { industry_name: "Telecommunications" },
      { industry_name: "Abrasives and Nonmetallic Minerals Manufacturing" },
      { industry_name: "Accommodation" },
      { industry_name: "Accounting" },
      { industry_name: "Administration of Justice" },
      { industry_name: "Administrative and Support Services" },
      { industry_name: "Advertising Services" },
      { industry_name: "Agricultural Chemical Manufacturing" },
      { industry_name: "Agriculture, Construction, Mining Machinery Manufacturing" },
      { industry_name: "Air, Water, and Waste Program Management" },
      { industry_name: "Airlines and Aviation" },
      { industry_name: "Alternative Dispute Resolution" },
      { industry_name: "Alternative Medicine" },
      { industry_name: "Ambulance Services" },
      { industry_name: "Amusement Parks and Arcades" },
      { industry_name: "Animal Feed Manufacturing" },
      { industry_name: "Animation and Post-production" },
      { industry_name: "Apparel Manufacturing" },
      { industry_name: "Appliances, Electrical, and Electronics Manufacturing" },
      { industry_name: "Architectural and Structural Metal Manufacturing" },
      { industry_name: "Architecture and Planning" },
      { industry_name: "Armed Forces" },
      { industry_name: "Artificial Rubber and Synthetic Fiber Manufacturing" },
      { industry_name: "Artists and Writers" },
      { industry_name: "Audio and Video Equipment Manufacturing" },
      { industry_name: "Automation Machinery Manufacturing" },
      { industry_name: "Aviation and Aerospace Component Manufacturing" },
      { industry_name: "Baked Goods Manufacturing" },
      { industry_name: "Banking" },
      { industry_name: "Bars, Taverns, and Nightclubs" },
      { industry_name: "Bed-and-Breakfasts, Hostels, Homestays" },
      { industry_name: "Beverage Manufacturing" },
      { industry_name: "Biomass Electric Power Generation" },
      { industry_name: "Biotechnology Research" },
      { industry_name: "Blockchain Services" },
      { industry_name: "Blogs" },
      { industry_name: "Boilers, Tanks, and Shipping Container Manufacturing" },
      { industry_name: "Book and Periodical Publishing" },
      { industry_name: "Book Publishing" },
      { industry_name: "Breweries" },
      { industry_name: "Broadcast Media Production and Distribution" },
      { industry_name: "Building Construction" },
      { industry_name: "Building Equipment Contractors" },
      { industry_name: "Building Finishing Contractors" },
      { industry_name: "Building Structure and Exterior Contractors" },
      { industry_name: "Business Consulting and Services" },
      { industry_name: "Business Content" },
      { industry_name: "Business Intelligence Platforms" },
      { industry_name: "Business Skills Training" },
      { industry_name: "Business Supplies & Equipment" },
      { industry_name: "Cable and Satellite Programming" },
      { industry_name: "Capital Markets" },
      { industry_name: "Caterers" },
      { industry_name: "Chemical Manufacturing" },
      { industry_name: "Chemical Raw Materials Manufacturing" },
      { industry_name: "Child Day Care Services" },
      { industry_name: "Chiropractors" },
      { industry_name: "Circuses and Magic Shows" },
      { industry_name: "Civic and Social Organizations" },
      { industry_name: "Civil Engineering" },
      { industry_name: "Claims Adjusting, Actuarial Services" },
      { industry_name: "Clay and Refractory Products Manufacturing" },
      { industry_name: "Coal Mining" },
      { industry_name: "Collection Agencies" },
      { industry_name: "Commercial and Industrial Equipment Rental" },
      { industry_name: "Commercial and Industrial Machinery Maintenance" },
      { industry_name: "Commercial and Service Industry Machinery Manufacturing" },
      { industry_name: "Communications Equipment Manufacturing" },
      { industry_name: "Community Development and Urban Planning" },
      { industry_name: "Community Services" },
      { industry_name: "Computer and Network Security" },
      { industry_name: "Computer Games" },
      { industry_name: "Computer Hardware Manufacturing" },
      { industry_name: "Computer Networking Products" },
      { industry_name: "Computers and Electronics Manufacturing" },
      { industry_name: "Conservation Programs" },
      { industry_name: "Construction" },
      { industry_name: "Construction Hardware Manufacturing" },
      { industry_name: "Consumer Goods Rental" },
      { industry_name: "Consumer Services" },
      { industry_name: "Correctional Institutions" },
      { industry_name: "Cosmetology and Barber Schools" },
      { industry_name: "Courts of Law" },
      { industry_name: "Credit Intermediation" },
      { industry_name: "Cutlery and Handtool Manufacturing" },
      { industry_name: "Dairy Product Manufacturing" },
      { industry_name: "Dance Companies" },
      { industry_name: "Data Infrastructure and Analytics" },
      { industry_name: "Data Security Software Products" },
      { industry_name: "Defense and Space Manufacturing" },
      { industry_name: "Dentists" },
      { industry_name: "Design Services" },
      { industry_name: "Desktop Computing Software Products" },
      { industry_name: "Distilleries" },
      { industry_name: "Economic Programs" },
      { industry_name: "Education" },
      { industry_name: "Education Administration Programs" },
      { industry_name: "E-Learning Providers" },
      { industry_name: "Electric Lighting Equipment Manufacturing" },
      { industry_name: "Electric Power Generation" },
      { industry_name: "Electric Power Transmission, Control, and Distribution" },
      { industry_name: "Electrical Equipment Manufacturing" },
      { industry_name: "Electronic and Precision Equipment Maintenance" },
      { industry_name: "Embedded Software Products" },
      { industry_name: "Emergency and Relief Services" },
      { industry_name: "Engines and Power Transmission Equipment Manufacturing" },
      { industry_name: "Entertainment Providers" },
      { industry_name: "Environmental Quality Programs" },
      { industry_name: "Environmental Services" },
      { industry_name: "Equipment Rental Services" },
      { industry_name: "Events Services" },
      { industry_name: "Executive Offices" },
      { industry_name: "Executive Search Services" },
      { industry_name: "Fabricated Metal Products" },
      { industry_name: "Facilities Services" },
      { industry_name: "Family Planning Centers" },
      { industry_name: "Farming" },
      { industry_name: "Farming, Ranching, Forestry" },
      { industry_name: "Fashion Accessories Manufacturing" },
      { industry_name: "Financial Services" },
      { industry_name: "Fine Arts Schools" },
      { industry_name: "Fire Protection" },
      { industry_name: "Fisheries" },
      { industry_name: "Flight Training" },
      { industry_name: "Food and Beverage Manufacturing" },
      { industry_name: "Food and Beverage Retail" },
      { industry_name: "Food and Beverage Services" },
      { industry_name: "Footwear and Leather Goods Repair" },
      { industry_name: "Footwear Manufacturing" },
      { industry_name: "Forestry and Logging" },
      { industry_name: "Fossil Fuel Electric Power Generation" },
      { industry_name: "Freight and Package Transportation" },
      { industry_name: "Fruit and Vegetable Preserves Manufacturing" },
      { industry_name: "Fundraising" },
      { industry_name: "Funds and Trusts" },
      { industry_name: "Furniture and Home Furnishings Manufacturing" },
      { industry_name: "Gambling Facilities and Casinos" },
      { industry_name: "Geothermal Electric Power Generation" },
      { industry_name: "Glass Product Manufacturing" },
      { industry_name: "Glass, Ceramics and Concrete Manufacturing" },
      { industry_name: "Golf Courses and Country Clubs" },
      { industry_name: "Government Administration" },
      { industry_name: "Government Relations Services" },
      { industry_name: "Graphic Design" },
      { industry_name: "Ground Passenger Transportation" },
      { industry_name: "Health and Human Services" },
      { industry_name: "Higher Education" },
      { industry_name: "Highway, Street, and Bridge Construction" },
      { industry_name: "Historical Sites" },
      { industry_name: "Holding Companies" },
      { industry_name: "Home Health Care Services" },
      { industry_name: "Horticulture" },
      { industry_name: "Hospitality" },
      { industry_name: "Hospitals" },
      { industry_name: "Hospitals and Health Care" },
      { industry_name: "Hotels and Motels" },
      { industry_name: "Household and Institutional Furniture Manufacturing" },
      { industry_name: "Household Appliance Manufacturing" },
      { industry_name: "Household Services" },
      { industry_name: "Housing and Community Development" },
      { industry_name: "Housing Programs" },
      { industry_name: "Human Resources Services" },
      { industry_name: "HVAC and Refrigeration Equipment Manufacturing" },
      { industry_name: "Hydroelectric Power Generation" },
      { industry_name: "Individual and Family Services" },
      { industry_name: "Industrial Machinery Manufacturing" },
      { industry_name: "Industry Associations" },
      { industry_name: "Information Services" },
      { industry_name: "Insurance" },
      { industry_name: "Insurance Agencies and Brokerages" },
      { industry_name: "Insurance and Employee Benefit Funds" },
      { industry_name: "Insurance Carriers" },
      { industry_name: "Interior Design" },
      { industry_name: "International Affairs" },
      { industry_name: "International Trade and Development" },
      { industry_name: "Internet Marketplace Platforms" },
      { industry_name: "Internet News" },
      { industry_name: "Internet Publishing" },
      { industry_name: "Interurban and Rural Bus Services" },
      { industry_name: "Investment Advice" },
      { industry_name: "Investment Banking" },
      { industry_name: "Investment Management" },
      { industry_name: "IT Services and IT Consulting" },
      { industry_name: "IT System Custom Software Development" },
      { industry_name: "IT System Data Services" },
      { industry_name: "IT System Design Services" },
      { industry_name: "IT System Installation and Disposal" },
      { industry_name: "IT System Operations and Maintenance" },
      { industry_name: "IT System Testing and Evaluation" },
      { industry_name: "IT System Training and Support" },
      { industry_name: "Janitorial Services" },
      { industry_name: "Landscaping Services" },
      { industry_name: "Language Schools" },
      { industry_name: "Laundry and Drycleaning Services" },
      { industry_name: "Law Enforcement" },
      { industry_name: "Law Practice" },
      { industry_name: "Leasing Non-residential Real Estate" },
      { industry_name: "Leasing Residential Real Estate" },
      { industry_name: "Leather Product Manufacturing" },
      { industry_name: "Legal Services" },
      { industry_name: "Legislative Offices" },
      { industry_name: "Libraries" },
      { industry_name: "Lime and Gypsum Products Manufacturing" },
      { industry_name: "Loan Brokers" },
      { industry_name: "Machinery Manufacturing" },
      { industry_name: "Magnetic and Optical Media Manufacturing" },
      { industry_name: "Manufacturing" },
      { industry_name: "Maritime Transportation" },
      { industry_name: "Market Research" },
      { industry_name: "Marketing Services" },
      { industry_name: "Mattress and Blinds Manufacturing" },
      { industry_name: "Measuring and Control Instrument Manufacturing" },
      { industry_name: "Meat Products Manufacturing" },
      { industry_name: "Media and Telecommunications" },
      { industry_name: "Media Production" },
      { industry_name: "Medical and Diagnostic Laboratories" },
      { industry_name: "Medical Equipment Manufacturing" },
      { industry_name: "Medical Practices" },
      { industry_name: "Mental Health Care" },
      { industry_name: "Metal Ore Mining" },
      { industry_name: "Metal Treatments" },
      { industry_name: "Metal Valve, Ball, and Roller Manufacturing" },
      { industry_name: "Metalworking Machinery Manufacturing" },
      { industry_name: "Military and International Affairs" },
      { industry_name: "Mining" },
      { industry_name: "Mobile Computing Software Products" },
      { industry_name: "Mobile Food Services" },
      { industry_name: "Mobile Gaming Apps" },
      { industry_name: "Motor Vehicle Manufacturing" },
      { industry_name: "Motor Vehicle Parts Manufacturing" },
      { industry_name: "Movies and Sound Recording" },
      { industry_name: "Movies, Videos, and Sound" },
      { industry_name: "Museums" },
      { industry_name: "Museums, Historical Sites, and Zoos" },
      { industry_name: "Musicians" },
      { industry_name: "Nanotechnology Research" },
      { industry_name: "Natural Gas Distribution" },
      { industry_name: "Natural Gas Extraction" },
      { industry_name: "Newspaper Publishing" },
      { industry_name: "Nonmetallic Mineral Mining" },
      { industry_name: "Non-profit Organizations" },
      { industry_name: "Nonresidential Building Construction" },
      { industry_name: "Nuclear Electric Power Generation" },
      { industry_name: "Nursing Homes and Residential Care Facilities" },
      { industry_name: "Office Administration" },
      { industry_name: "Office Furniture and Fixtures Manufacturing" },
      { industry_name: "Oil and Coal Product Manufacturing" },
      { industry_name: "Oil and Gas" },
      { industry_name: "Oil Extraction" },
      { industry_name: "Oil, Gas, and Mining" },
      { industry_name: "Online and Mail Order Retail" },
      { industry_name: "Online Audio and Video Media" },
      { industry_name: "Operations Consulting" },
      { industry_name: "Optometrists" },
      { industry_name: "Outpatient Care Centers" },
      { industry_name: "Outsourcing and Offshoring Consulting" },
      { industry_name: "Packaging and Containers Manufacturing" },
      { industry_name: "Paint, Coating, and Adhesive Manufacturing" },
      { industry_name: "Paper and Forest Product Manufacturing" },
      { industry_name: "Pension Funds" },
      { industry_name: "Performing Arts" },
      { industry_name: "Performing Arts and Spectator Sports" },
      { industry_name: "Periodical Publishing" },
      { industry_name: "Personal and Laundry Services" },
      { industry_name: "Personal Care Product Manufacturing" },
      { industry_name: "Personal Care Services" },
      { industry_name: "Pet Services" },
      { industry_name: "Pharmaceutical Manufacturing" },
      { industry_name: "Philanthropic Fundraising Services" },
      { industry_name: "Photography" },
      { industry_name: "Physical, Occupational and Speech Therapists" },
      { industry_name: "Physicians" },
      { industry_name: "Pipeline Transportation" },
      { industry_name: "Plastics and Rubber Product Manufacturing" },
      { industry_name: "Plastics Manufacturing" },
      { industry_name: "Political Organizations" },
      { industry_name: "Postal Services" },
      { industry_name: "Primary and Secondary Education" },
      { industry_name: "Primary Metal Manufacturing" },
      { industry_name: "Printing Services" },
      { industry_name: "Professional Organizations" },
      { industry_name: "Professional Services" },
      { industry_name: "Public Assistance Programs" },
      { industry_name: "Public Health" },
      { industry_name: "Public Policy Offices" },
      { industry_name: "Public Relations and Communications Services" },
      { industry_name: "Public Safety" },
      { industry_name: "Racetracks" },
      { industry_name: "Radio and Television Broadcasting" },
      { industry_name: "Rail Transportation" },
      { industry_name: "Railroad Equipment Manufacturing" },
      { industry_name: "Ranching" },
      { industry_name: "Ranching and Fisheries" },
      { industry_name: "Real Estate" },
      { industry_name: "Real Estate Agents and Brokers" },
      { industry_name: "Real Estate and Equipment Rental Services" },
      { industry_name: "Recreational Facilities" },
      { industry_name: "Religious Institutions" },
      { industry_name: "Renewable Energy Semiconductor Manufacturing" },
      { industry_name: "Repair and Maintenance" },
      { industry_name: "Research Services" },
      { industry_name: "Residential Building Construction" },
      { industry_name: "Restaurants" },
      { industry_name: "Retail" },
      { industry_name: "Retail Apparel and Fashion" },
      { industry_name: "Retail Appliances, Electrical, and Electronic Equipment" },
      { industry_name: "Retail Art Supplies" },
      { industry_name: "Retail Books and Printed News" },
      { industry_name: "Retail Building Materials and Garden Equipment" },
      { industry_name: "Retail Florists" },
      { industry_name: "Retail Furniture and Home Furnishings" },
      { industry_name: "Retail Gasoline" },
      { industry_name: "Retail Groceries" },
      { industry_name: "Retail Health and Personal Care Products" },
      { industry_name: "Retail Luxury Goods and Jewelry" },
      { industry_name: "Retail Motor Vehicles" },
      { industry_name: "Retail Musical Instruments" },
      { industry_name: "Retail Office Equipment" },
      { industry_name: "Retail Office Supplies and Gifts" },
      { industry_name: "Retail Recyclable Materials & Used Merchandise" },
      { industry_name: "Reupholstery and Furniture Repair" },
      { industry_name: "Rubber Products Manufacturing" },
      { industry_name: "Satellite Telecommunications" },
      { industry_name: "Savings Institutions" },
      { industry_name: "School and Employee Bus Services" },
      { industry_name: "Seafood Product Manufacturing" },
      { industry_name: "Secretarial Schools" },
      { industry_name: "Securities and Commodity Exchanges" },
      { industry_name: "Security and Investigations" },
      { industry_name: "Security Guards and Patrol Services" },
      { industry_name: "Security Systems Services" },
      { industry_name: "Semiconductor Manufacturing" },
      { industry_name: "Services for the Elderly and Disabled" },
      { industry_name: "Sheet Music Publishing" },
      { industry_name: "Shipbuilding" },
      { industry_name: "Shuttles and Special Needs Transportation Services" },
      { industry_name: "Sightseeing Transportation" },
      { industry_name: "Skiing Facilities" },
      { industry_name: "Soap and Cleaning Product Manufacturing" },
      { industry_name: "Social Networking Platforms" },
      { industry_name: "Software Development" },
      { industry_name: "Solar Electric Power Generation" },
      { industry_name: "Sound Recording" },
      { industry_name: "Space Research and Technology" },
      { industry_name: "Specialty Trade Contractors" },
      { industry_name: "Spectator Sports" },
      { industry_name: "Sporting Goods Manufacturing" },
      { industry_name: "Sports and Recreation Instruction" },
      { industry_name: "Sports Teams and Clubs" },
      { industry_name: "Spring and Wire Product Manufacturing" },
      { industry_name: "Staffing and Recruiting" },
      { industry_name: "Steam and Air-Conditioning Supply" },
      { industry_name: "Strategic Management Services" },
      { industry_name: "Subdivision of Land" },
      { industry_name: "Sugar and Confectionery Product Manufacturing" },
      { industry_name: "Taxi and Limousine Services" },
      { industry_name: "Technical and Vocational Training" },
      { industry_name: "Technology and Information" },
      { industry_name: "Technology, Information and Media" },
      { industry_name: "Telecommunications Carriers" },
      { industry_name: "Telephone Call Centers" },
      { industry_name: "Temporary Help Services" },
      { industry_name: "Textile Manufacturing" },
      { industry_name: "Theater Companies" },
      { industry_name: "Think Tanks" },
      { industry_name: "Tobacco Manufacturing" },
      { industry_name: "Translation and Localization" },
      { industry_name: "Transportation Equipment Manufacturing" },
      { industry_name: "Transportation Programs" },
      { industry_name: "Transportation, Logistics and Storage" },
      { industry_name: "Travel Arrangements" },
      { industry_name: "Truck Transportation" },
      { industry_name: "Trusts and Estates" },
      { industry_name: "Turned Products and Fastener Manufacturing" },
      { industry_name: "Urban Transit Services" },
      { industry_name: "Utilities" },
      { industry_name: "Utilities Administration" },
      { industry_name: "Utility System Construction" },
      { industry_name: "Vehicle Repair and Maintenance" },
      { industry_name: "Venture Capital and Private Equity Principals" },
      { industry_name: "Veterinary Services" },
      { industry_name: "Vocational Rehabilitation Services" },
      { industry_name: "Warehousing and Storage" },
      { industry_name: "Waste Collection" },
      { industry_name: "Waste Treatment and Disposal" },
      { industry_name: "Water Supply and Irrigation Systems" },
      { industry_name: "Water, Waste, Steam, and Air Conditioning Services" },
      { industry_name: "Wellness and Fitness Services" },
      { industry_name: "Wholesale" },
      { industry_name: "Wholesale Alcoholic Beverages" },
      { industry_name: "Wholesale Apparel and Sewing Supplies" },
      { industry_name: "Wholesale Appliances, Electrical, and Electronics" },
      { industry_name: "Wholesale Building Materials" },
      { industry_name: "Wholesale Chemical and Allied Products" },
      { industry_name: "Wholesale Computer Equipment" },
      { industry_name: "Wholesale Drugs and Sundries" },
      { industry_name: "Wholesale Food and Beverage" },
      { industry_name: "Wholesale Footwear" },
      { industry_name: "Wholesale Furniture and Home Furnishings" },
      { industry_name: "Wholesale Hardware, Plumbing, Heating Equipment" },
      { industry_name: "Wholesale Import and Export" },
      { industry_name: "Wholesale Luxury Goods and Jewelry" },
      { industry_name: "Wholesale Machinery" },
      { industry_name: "Wholesale Metals and Minerals" },
      { industry_name: "Wholesale Motor Vehicles and Parts" },
      { industry_name: "Wholesale Paper Products" },
      { industry_name: "Wholesale Petroleum and Petroleum Products" },
      { industry_name: "Wholesale Photography Equipment and Supplies" },
      { industry_name: "Wholesale Raw Farm Products" },
      { industry_name: "Wholesale Recyclable Materials" },
      { industry_name: "Wind Electric Power Generation" },
      { industry_name: "Wineries" },
      { industry_name: "Wireless Services" },
      { industry_name: "Women's Handbag Manufacturing" },
      { industry_name: "Wood Product Manufacturing" },
      { industry_name: "Writing and Editing" },
      { industry_name: "Zoos and Botanical Gardens" }
    ],
    skipDuplicates: true,
  });

  console.log("✅ Industries seeded successfully.");
}